C++						:= g++
FLAGS					:= -std=c++17 -Wall
INCLUDE				:= -I./math/
MAIN					:= main.cpp
DEPENDENCIES	:=
EXEC					:= main

all:
	${C++} ${MAIN} ${DEPENDENCIES} ${INCLUDE} ${FLAGS} -o ${EXEC}

clean:
	rm ${EXEC}
